import {
  Container,
  Badge,
  Link,
  List,
  ListItem,
  SimpleGrid,
  Text,
  Divider
} from '@chakra-ui/react'
import { ExternalLinkIcon } from '@chakra-ui/icons'
import { Title, ProjectImage, Meta } from '../../components/project'
import P from '../../components/paragraph'
import Layout from '../../components/layouts/article'
import NextLink from 'next/link'

const Project = () => (
  <Layout title="Sporter">
    <Container>
      <Title>
        CatPic <Badge>2022</Badge>
      </Title>
      <P>
        An iOS app for viewing random cat picture based on their breed using
        SwiftUI. Random cat images are generated by calling the{' '}
        <NextLink href="https://thecatapi.com/" passHref scroll={false}>
          <Link isExternal="true">The Cat API</Link>
        </NextLink>
        .
      </P>
      <P>
        This is the result of an individual project I created for the iOS course
        at school.
      </P>
      <List ml={4} my={4}>
        <ListItem>
          <Meta>Source Code</Meta>
          <Link
            href="https://github.com/khangnguyen111101/CatPic/"
            isExternal="true"
          >
            GitHub <ExternalLinkIcon mx="2px" />
          </Link>
        </ListItem>
        <ListItem>
          <Meta>Type</Meta>
          <span>Individual</span>
        </ListItem>
        <ListItem>
          <Meta>Role</Meta>
          <span>Front-end and Back-end lead</span>
        </ListItem>
        <ListItem>
          <Meta>Platform</Meta>
          <span>iOS</span>
        </ListItem>
        <ListItem>
          <Meta>Stack</Meta>
          <span>SwiftUI, LottieFiles</span>
        </ListItem>
      </List>

      <Divider mb={3}></Divider>

      <Text align="center" fontSize="14px" mb={1}>
        Cat List
      </Text>
      <SimpleGrid columns={3} spacingX={1}>
        <ProjectImage src="/images/catpic/catpic-1.png" alt="CatPic" />
        <ProjectImage src="/images/catpic/catpic-2.png" alt="CatPic" />
        <ProjectImage src="/images/catpic/catpic-3.png" alt="CatPic" />
      </SimpleGrid>

      <Text align="center" fontSize="14px" mb={1}>
        Cat Profile
      </Text>
      <SimpleGrid columns={2} spacingX={1}>
        <ProjectImage src="/images/catpic/catpic-4.png" alt="CatPic" />
        <ProjectImage src="/images/catpic/catpic-5.png" alt="CatPic" />
      </SimpleGrid>
    </Container>
  </Layout>
)

export default Project
export { getServerSideProps } from '../../components/chakra'
